repos:
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 4.0.1.1
    hooks:
      - id: buildifier
        args: &args
          # Keep this argument in sync with .bazelci/presubmit.yaml
          - --warnings=all
      - id: buildifier-lint
        args: *args
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        args:
          - --allow-multiple-documents
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
