// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package efvi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EfviServiceClient is the client API for EfviService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EfviServiceClient interface {
	ApplyVirtualDevice(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ViResource, error)
}

type efviServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEfviServiceClient(cc grpc.ClientConnInterface) EfviServiceClient {
	return &efviServiceClient{cc}
}

func (c *efviServiceClient) ApplyVirtualDevice(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ViResource, error) {
	out := new(ViResource)
	err := c.cc.Invoke(ctx, "/efvi.EfviService/ApplyVirtualDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EfviServiceServer is the server API for EfviService service.
// All implementations must embed UnimplementedEfviServiceServer
// for forward compatibility
type EfviServiceServer interface {
	ApplyVirtualDevice(context.Context, *ApplyRequest) (*ViResource, error)
	mustEmbedUnimplementedEfviServiceServer()
}

// UnimplementedEfviServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEfviServiceServer struct {
}

func (UnimplementedEfviServiceServer) ApplyVirtualDevice(context.Context, *ApplyRequest) (*ViResource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyVirtualDevice not implemented")
}
func (UnimplementedEfviServiceServer) mustEmbedUnimplementedEfviServiceServer() {}

// UnsafeEfviServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EfviServiceServer will
// result in compilation errors.
type UnsafeEfviServiceServer interface {
	mustEmbedUnimplementedEfviServiceServer()
}

func RegisterEfviServiceServer(s grpc.ServiceRegistrar, srv EfviServiceServer) {
	s.RegisterService(&EfviService_ServiceDesc, srv)
}

func _EfviService_ApplyVirtualDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EfviServiceServer).ApplyVirtualDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/efvi.EfviService/ApplyVirtualDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EfviServiceServer).ApplyVirtualDevice(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EfviService_ServiceDesc is the grpc.ServiceDesc for EfviService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EfviService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "efvi.EfviService",
	HandlerType: (*EfviServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyVirtualDevice",
			Handler:    _EfviService_ApplyVirtualDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/efvi.proto",
}
