// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: proto/efvi.proto

package efvi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host      string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port      int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Interface string `protobuf:"bytes,3,opt,name=interface,proto3" json:"interface,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_efvi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_efvi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_efvi_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ApplyRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ApplyRequest) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *ApplyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ViResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ViPath    string `protobuf:"bytes,3,opt,name=viPath,proto3" json:"viPath,omitempty"`
	QueuePath string `protobuf:"bytes,4,opt,name=queuePath,proto3" json:"queuePath,omitempty"`
}

func (x *ViResource) Reset() {
	*x = ViResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_efvi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViResource) ProtoMessage() {}

func (x *ViResource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_efvi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViResource.ProtoReflect.Descriptor instead.
func (*ViResource) Descriptor() ([]byte, []int) {
	return file_proto_efvi_proto_rawDescGZIP(), []int{1}
}

func (x *ViResource) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ViResource) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ViResource) GetViPath() string {
	if x != nil {
		return x.ViPath
	}
	return ""
}

func (x *ViResource) GetQueuePath() string {
	if x != nil {
		return x.QueuePath
	}
	return ""
}

var File_proto_efvi_proto protoreflect.FileDescriptor

var file_proto_efvi_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x66, 0x76, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x65, 0x66, 0x76, 0x69, 0x22, 0x68, 0x0a, 0x0c, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x70, 0x0a, 0x0a, 0x56, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x69, 0x50, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x76, 0x69, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x71, 0x75, 0x65, 0x75, 0x65, 0x50,
	0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x32, 0x4b, 0x0a, 0x0b, 0x45, 0x66, 0x76, 0x69, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x12, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x56, 0x69, 0x72, 0x74,
	0x75, 0x61, 0x6c, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x2e, 0x65, 0x66, 0x76, 0x69,
	0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e,
	0x65, 0x66, 0x76, 0x69, 0x2e, 0x56, 0x69, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22,
	0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x66, 0x72, 0x61, 0x6e, 0x63, 0x6f, 0x63, 0x63, 0x63, 0x2f, 0x73, 0x66, 0x63, 0x2d, 0x76, 0x69,
	0x72, 0x74, 0x75, 0x61, 0x6c, 0x2d, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2f, 0x65, 0x66, 0x76, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_efvi_proto_rawDescOnce sync.Once
	file_proto_efvi_proto_rawDescData = file_proto_efvi_proto_rawDesc
)

func file_proto_efvi_proto_rawDescGZIP() []byte {
	file_proto_efvi_proto_rawDescOnce.Do(func() {
		file_proto_efvi_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_efvi_proto_rawDescData)
	})
	return file_proto_efvi_proto_rawDescData
}

var file_proto_efvi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_efvi_proto_goTypes = []interface{}{
	(*ApplyRequest)(nil), // 0: efvi.ApplyRequest
	(*ViResource)(nil),   // 1: efvi.ViResource
}
var file_proto_efvi_proto_depIdxs = []int32{
	0, // 0: efvi.EfviService.ApplyVirtualDevice:input_type -> efvi.ApplyRequest
	1, // 1: efvi.EfviService.ApplyVirtualDevice:output_type -> efvi.ViResource
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_efvi_proto_init() }
func file_proto_efvi_proto_init() {
	if File_proto_efvi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_efvi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_efvi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_efvi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_efvi_proto_goTypes,
		DependencyIndexes: file_proto_efvi_proto_depIdxs,
		MessageInfos:      file_proto_efvi_proto_msgTypes,
	}.Build()
	File_proto_efvi_proto = out.File
	file_proto_efvi_proto_rawDesc = nil
	file_proto_efvi_proto_goTypes = nil
	file_proto_efvi_proto_depIdxs = nil
}
