apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: gw-inter
spec:
  config: '{
      "cniVersion": "0.3.0",
      "name": "gw-inter",
      "plugins": [
        {
          "type": "sfc-macvlan",
          "mode": "bridge"
        }
      ]
    }'
