apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vsfc-device-plugin
  namespace: kube-system
  labels:
    tier: node
spec:
  selector:
    matchLabels:
      app: vsfc-device-plugin
  template:
    metadata:
      labels:
        tier: node
        app: vsfc-device-plugin
    spec:
      hostIPC: true
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: device-plugin-ctr
        image: registry.corp.highfortfunds.com/highfort/plugin/vsfc:latest
        imagePullPolicy: Always
        command: ["/app/plugin"]
        resources:
          limits:
            memory: 1024Mi
            cpu: "100m"
            hugepages-2Mi: "100Mi"
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: "/root/.ssh/id_rsa"
            name: ssh-key
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
          - name: pki
            mountPath: "/etc/kubernetes/pki"
          - name: shm
            mountPath: "/dev/shm"
          - name: hugepages
            mountPath: "/mnt/hugepages"
          - name: sfc-char
            mountPath: "/dev/sfc_char"
          - name: sfc-affinity
            mountPath: "/dev/sfc_affinity"
          - name: config-file
            mountPath: "/etc/solarflare"
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      initContainers:
        - name: generate-kubeconfig
          image: registry.corp.highfortfunds.com/highfort/plugin/vsfc/code-generation:latest
          command: ["/app/code-generation"]
          args:
            - "-k8s-service-host=$(KUBERNETES_SERVICE_HOST)"
            - "-k8s-service-port=$(KUBERNETES_SERVICE_PORT)"
          resources:
            requests:
              cpu: "10m"
              memory: "15Mi"
          securityContext:
            privileged: true
          volumeMounts:
            - name: config-file
              mountPath: "/etc/solarflare"
              mountPropagation: Bidirectional
      volumes:
        - name: ssh-key
          hostPath:
            path: "/root/.ssh/id_rsa"
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: pki
          hostPath:
            path: "/etc/kubernetes/pki"
        - name: shm
          hostPath:
            path: "/dev/shm"
        - name: hugepages
          hostPath:
            path: "/mnt/hugepages"
        - name: sfc-char
          hostPath:
            path: "/dev/sfc_char"
        - name: sfc-affinity
          hostPath:
            path: "/dev/sfc_affinity"
        - name: config-file
          hostPath:
            path: "/etc/solarflare"
      serviceAccountName: vsfc-cdp
